# Generated by Django 5.1.4 on 2024-12-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=50)),
                ('p_quantity', models.IntegerField()),
                ('p_image', models.ImageField(null=True, upload_to='productimages/')),
                ('p_video', models.FileField(null=True, upload_to='productvideo/')),
                ('p_description', models.TextField()),
                ('p_brand', models.CharField(max_length=15)),
                ('fk_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.productdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=50)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fk_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.subcategory'),
        ),
        migrations.CreateModel(
            name='BatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alert', models.IntegerField()),
                ('batch_number', models.CharField(max_length=25)),
                ('b_quantity', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('packet_numbers', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('manufacture_date', models.DateField()),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.productdetails')),
                ('fk_unit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.unitcategory')),
            ],
        ),
    ]
